//NAVIGATION
export const GO_TO = 'GO_TO';
export const GO_BACK = 'GO_BACK';
export const CUSTOM_GO_BACK = 'CUSTOM_GO_BACK';
export const SET_PARAMS = 'SET_PARAMS';

//USER
export const SET_AGE = 'SET_AGE';
export const SET_GENDER = 'SET_GENDER';

//CENTERS
export const SEARCH_CENTER = 'SEARCH_CENTER';
export const SELECT_CENTER = 'SELECT_CENTER';
export const GET_CENTERS = 'GET_CENTERS';
export const FILTER_CENTERS_BY_USER = 'FILTER_CENTER_BY_USER';
export const FILTER_CENTERS_BY_CATAGORY = 'FILTER_CENTERS_BY_CATAGORY';
export const GET_CATAGORIES = 'GET_CATAGORIES';
export const RESET_CATAGORIES = 'RESET_CATAGORIES';
export const POP_CATAGORY = 'POP_CATAGORY';
