//NAVIGATION
export const GO_TO = 'GO_TO';
export const SET_PARAMS = 'SET_PARAMS';

//USER
export const SET_AGE = 'SET_AGE';
export const SET_GENDER = 'SET_GENDER';

//CENTERS
export const SEARCH_CENTER = 'SEARCH_CENTER';
export const SELECT_CENTER = 'SELECT_CENTER';
export const GET_CENTERS = 'GET_CENTERS';
export const FILTER_CENTERS_BY_AGE = 'FILTER_CENTERS_BY_AGE';
export const FILTER_CENTERS_BY_GENDER ='FILTER_CENTERS_BY_GENDER';
export const FILTER_CENTERS_BY_CATAGORY = 'FILTER_CENTERS_BY_CATAGORY';
export const GET_CATAGORIES = 'GET_CATAGORIES';
