//NAVIGATION
export const GO_TO = 'GO_TO';

//USER
export const SET_AGE = 'SET_AGE';
export const SET_GENDER = 'SET_GENDER';

//CENTERS
export const SEARCH_CENTER = 'SEARCH_CENTER';
export const SELECT_CENTER = 'SELECT_CENTER';
export const GET_CENTERS = 'GET_CENTERS';

//CATAGORIES
export const GET_CATAGORIES = 'GET_CATAGORIES';
export const GET_SUB_CATAGORIES = 'GET_SUB_CATAGORIES'; 